# exported from PySB model 'model'

import numpy as np
from pysb.integrate import Solver
import pylab as pl
import matplotlib.pyplot as plt
from pysb import Model, Monomer, Parameter, Expression, Compartment, Rule, Observable, Initial, MatchOnce, Annotation, ANY, WILD

Model()

Monomer('BaxC', ['BidM'])
Monomer('BaxA', ['BaxA_1', 'BaxA_2', 'BclxLM', 'Bcl2', 'CytoCM', 'BaxM', 'SmacM'])
Monomer('Mcl1M', ['BidM', 'NoxaM', 'BakA'])
Monomer('NoxaM', ['Mcl1M'])
Monomer('BaxM', ['BidM', 'BaxA'])
Monomer('BidM', ['BaxM', 'BaxC', 'Mcl1M', 'Bcl2', 'BclxLM', 'BakM'])
Monomer('BakM', ['BakA', 'BidM'])
Monomer('SmacM', ['BakA', 'BaxA'])
Monomer('CytoCM', ['BakA', 'BaxA'])
Monomer('BclxLM', ['BaxA', 'BidM', 'BadM', 'BakA'])
Monomer('BadM', ['BclxLM', 'Bcl2'])
Monomer('CytoCC')
Monomer('SmacC')
Monomer('BakA', ['BakA_1', 'BakA_2', 'CytoCM', 'BakM', 'SmacM', 'BclxLM', 'Mcl1M'])
Monomer('Bcl2', ['BaxA', 'BidM', 'BadM'])

Parameter('BaxA_formation_0_2kf', 1.0)
Parameter('BaxA_formation_0_1kr', 1.0)
Parameter('BaxA_formation_1_2kf', 1.0)
Parameter('BaxA_formation_1_1kr', 1.0)
Parameter('BaxA_formation_2_2kf', 1.0)
Parameter('BaxA_formation_2_1kr', 1.0)
Parameter('BakA_formation_0_2kf', 1.0)
Parameter('BakA_formation_0_1kr', 1.0)
Parameter('BakA_formation_1_2kf', 1.0)
Parameter('BakA_formation_1_1kr', 1.0)
Parameter('BakA_formation_2_2kf', 1.0)
Parameter('BakA_formation_2_1kr', 1.0)
Parameter('BclxLM_inhibition_BaxA_0_2kf', 1.0)
Parameter('BclxLM_inhibition_BaxA_0_1kr', 1.0)
Parameter('Bcl2_inhibition_BaxA_0_2kf', 1.0)
Parameter('Bcl2_inhibition_BaxA_0_1kr', 1.0)
Parameter('BidM_BaxM_catalysis_BaxA_0_1kc', 1.0)
Parameter('BidM_substrate_binding_BaxM_0_2kf', 1.0)
Parameter('BidM_substrate_binding_BaxM_0_1kr', 1.0)
Parameter('CytoCM_BakA_transport_CytoCC_0_1kc', 1.0)
Parameter('CytoCM_BaxA_transport_CytoCC_0_1kc', 1.0)
Parameter('BakA_transport_binding_CytoCM_0_2kf', 1.0)
Parameter('BakA_transport_binding_CytoCM_0_1kr', 1.0)
Parameter('BaxA_transport_binding_CytoCM_0_2kf', 1.0)
Parameter('BaxA_transport_binding_CytoCM_0_1kr', 1.0)
Parameter('BaxA_self_catalyze_BaxM_0_2kf', 1.0)
Parameter('BaxA_self_catalyze_BaxM_0_1kr', 1.0)
Parameter('BaxA_self_catalyze_BaxM_1_1kc', 1.0)
Parameter('BaxC_BidM_catalysis_BaxM_0_1kc', 1.0)
Parameter('BidM_substrate_binding_BaxC_0_2kf', 1.0)
Parameter('BidM_substrate_binding_BaxC_0_1kr', 1.0)
Parameter('Mcl1M_inhibition_BidM_0_2kf', 1.0)
Parameter('Mcl1M_inhibition_BidM_0_1kr', 1.0)
Parameter('Bcl2_inhibition_BidM_0_2kf', 1.0)
Parameter('Bcl2_inhibition_BidM_0_1kr', 1.0)
Parameter('BclxLM_inhibition_BidM_0_2kf', 1.0)
Parameter('BclxLM_inhibition_BidM_0_1kr', 1.0)
Parameter('BakA_self_catalyze_BakM_0_2kf', 1.0)
Parameter('BakA_self_catalyze_BakM_0_1kr', 1.0)
Parameter('BakA_self_catalyze_BakM_1_1kc', 1.0)
Parameter('BadM_inhibition_BclxLM_0_2kf', 1.0)
Parameter('BadM_inhibition_BclxLM_0_1kr', 1.0)
Parameter('NoxaM_inhibition_Mcl1M_0_2kf', 1.0)
Parameter('NoxaM_inhibition_Mcl1M_0_1kr', 1.0)
Parameter('SmacM_BakA_transport_SmacC_0_1kc', 1.0)
Parameter('SmacM_BaxA_transport_SmacC_0_1kc', 1.0)
Parameter('BakA_transport_binding_SmacM_0_2kf', 1.0)
Parameter('BakA_transport_binding_SmacM_0_1kr', 1.0)
Parameter('BaxA_transport_binding_SmacM_0_2kf', 1.0)
Parameter('BaxA_transport_binding_SmacM_0_1kr', 1.0)
Parameter('BclxLM_inhibition_BakA_0_2kf', 1.0)
Parameter('BclxLM_inhibition_BakA_0_1kr', 1.0)
Parameter('Mcl1M_inhibition_BakA_0_2kf', 1.0)
Parameter('Mcl1M_inhibition_BakA_0_1kr', 1.0)
Parameter('BakM_BidM_catalysis_BakA_0_1kc', 1.0)
Parameter('BidM_substrate_binding_BakM_0_2kf', 1.0)
Parameter('BidM_substrate_binding_BakM_0_1kr', 1.0)
Parameter('BadM_inhibition_Bcl2_0_2kf', 1.0)
Parameter('BadM_inhibition_Bcl2_0_1kr', 1.0)
Parameter('BaxC_0', 80000.0)
Parameter('BaxA_0', 0.0)
Parameter('Mcl1M_0', 20000.0)
Parameter('NoxaM_0', 0.0)
Parameter('BaxM_0', 0.0)
Parameter('BidM_0', 40000.0)
Parameter('BakM_0', 20000.0)
Parameter('SmacM_0', 100000.0)
Parameter('CytoCM_0', 500000.0)
Parameter('BclxLM_0', 20000.0)
Parameter('BadM_0', 0.0)
Parameter('CytoCC_0', 0.0)
Parameter('SmacC_0', 0.0)
Parameter('BakA_0', 0.0)
Parameter('Bcl2_0', 20000.0)

Observable('BaxC_obs', BaxC())
Observable('BaxA_obs', BaxA())
Observable('Mcl1M_obs', Mcl1M())
Observable('NoxaM_obs', NoxaM())
Observable('BaxM_obs', BaxM())
Observable('BidM_obs', BidM())
Observable('BakM_obs', BakM())
Observable('SmacM_obs', SmacM())
Observable('CytoCM_obs', CytoCM())
Observable('BclxLM_obs', BclxLM())
Observable('BadM_obs', BadM())
Observable('CytoCC_obs', CytoCC())
Observable('SmacC_obs', SmacC())
Observable('BakA_obs', BakA())
Observable('Bcl2_obs', Bcl2())

Rule('BaxA_formation_0', BaxA(BaxA_1=None, BaxA_2=None, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) + BaxA(BaxA_1=None, BaxA_2=None, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) | BaxA(BaxA_1=None, BaxA_2=1, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=1, BaxA_2=None, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None), BaxA_formation_0_2kf, BaxA_formation_0_1kr)
Rule('BaxA_formation_1', BaxA(BaxA_1=None, BaxA_2=None, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) + BaxA(BaxA_1=None, BaxA_2=1, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=1, BaxA_2=None, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) | BaxA(BaxA_1=3, BaxA_2=1, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=1, BaxA_2=2, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=2, BaxA_2=3, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None), BaxA_formation_1_2kf, BaxA_formation_1_1kr)
Rule('BaxA_formation_2', BaxA(BaxA_1=None, BaxA_2=None, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) + BaxA(BaxA_1=3, BaxA_2=1, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=1, BaxA_2=2, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=2, BaxA_2=3, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) | BaxA(BaxA_1=4, BaxA_2=1, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=1, BaxA_2=2, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=2, BaxA_2=3, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=3, BaxA_2=4, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None), BaxA_formation_2_2kf, BaxA_formation_2_1kr)
Rule('BakA_formation_0', BakA(BakA_1=None, BakA_2=None, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) + BakA(BakA_1=None, BakA_2=None, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) | BakA(BakA_1=None, BakA_2=1, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=1, BakA_2=None, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None), BakA_formation_0_2kf, BakA_formation_0_1kr)
Rule('BakA_formation_1', BakA(BakA_1=None, BakA_2=None, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) + BakA(BakA_1=None, BakA_2=1, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=1, BakA_2=None, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) | BakA(BakA_1=3, BakA_2=1, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=1, BakA_2=2, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=2, BakA_2=3, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None), BakA_formation_1_2kf, BakA_formation_1_1kr)
Rule('BakA_formation_2', BakA(BakA_1=None, BakA_2=None, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) + BakA(BakA_1=3, BakA_2=1, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=1, BakA_2=2, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=2, BakA_2=3, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) | BakA(BakA_1=4, BakA_2=1, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=1, BakA_2=2, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=2, BakA_2=3, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=3, BakA_2=4, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None), BakA_formation_2_2kf, BakA_formation_2_1kr)
Rule('BclxLM_inhibition_BaxA_0', BclxLM(BaxA=None, BidM=None, BadM=None, BakA=None) + BaxA(BaxA_1=None, BaxA_2=None, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) | BclxLM(BaxA=1, BidM=None, BadM=None, BakA=None) % BaxA(BaxA_1=None, BaxA_2=None, BclxLM=1, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None), BclxLM_inhibition_BaxA_0_2kf, BclxLM_inhibition_BaxA_0_1kr)
Rule('Bcl2_inhibition_BaxA_0', Bcl2(BaxA=None, BidM=None, BadM=None) + BaxA(BaxA_1=None, BaxA_2=None, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) | Bcl2(BaxA=1, BidM=None, BadM=None) % BaxA(BaxA_1=None, BaxA_2=None, BclxLM=None, Bcl2=1, CytoCM=None, BaxM=None, SmacM=None), Bcl2_inhibition_BaxA_0_2kf, Bcl2_inhibition_BaxA_0_1kr)
Rule('BidM_BaxM_catalysis_BaxA_0', BidM(BaxM=1, BaxC=None, Mcl1M=None, Bcl2=None, BclxLM=None, BakM=None) % BaxM(BidM=1, BaxA=None) >> BidM(BaxM=None, BaxC=None, Mcl1M=None, Bcl2=None, BclxLM=None, BakM=None) + BaxA(BaxA_1=None, BaxA_2=None, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None), BidM_BaxM_catalysis_BaxA_0_1kc)
Rule('BidM_substrate_binding_BaxM_0', BidM(BaxM=None, BaxC=None, Mcl1M=None, Bcl2=None, BclxLM=None, BakM=None) + BaxM(BidM=None, BaxA=None) | BidM(BaxM=1, BaxC=None, Mcl1M=None, Bcl2=None, BclxLM=None, BakM=None) % BaxM(BidM=1, BaxA=None), BidM_substrate_binding_BaxM_0_2kf, BidM_substrate_binding_BaxM_0_1kr)
Rule('CytoCM_BakA_transport_CytoCC_0', BakA(BakA_1=4, BakA_2=1, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=1, BakA_2=2, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=2, BakA_2=3, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=3, BakA_2=4, CytoCM=5, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % CytoCM(BakA=5, BaxA=None) >> BakA(BakA_1=4, BakA_2=1, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=1, BakA_2=2, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=2, BakA_2=3, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=3, BakA_2=4, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) + CytoCC(), CytoCM_BakA_transport_CytoCC_0_1kc)
Rule('CytoCM_BaxA_transport_CytoCC_0', BaxA(BaxA_1=4, BaxA_2=1, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=1, BaxA_2=2, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=2, BaxA_2=3, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=3, BaxA_2=4, BclxLM=None, Bcl2=None, CytoCM=5, BaxM=None, SmacM=None) % CytoCM(BakA=None, BaxA=5) >> BaxA(BaxA_1=4, BaxA_2=1, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=1, BaxA_2=2, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=2, BaxA_2=3, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=3, BaxA_2=4, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) + CytoCC(), CytoCM_BaxA_transport_CytoCC_0_1kc)
Rule('BakA_transport_binding_CytoCM_0', BakA(BakA_1=4, BakA_2=1, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=1, BakA_2=2, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=2, BakA_2=3, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=3, BakA_2=4, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) + CytoCM(BakA=None, BaxA=None) | BakA(BakA_1=4, BakA_2=1, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=1, BakA_2=2, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=2, BakA_2=3, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=3, BakA_2=4, CytoCM=5, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % CytoCM(BakA=5, BaxA=None), BakA_transport_binding_CytoCM_0_2kf, BakA_transport_binding_CytoCM_0_1kr)
Rule('BaxA_transport_binding_CytoCM_0', BaxA(BaxA_1=4, BaxA_2=1, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=1, BaxA_2=2, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=2, BaxA_2=3, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=3, BaxA_2=4, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) + CytoCM(BakA=None, BaxA=None) | BaxA(BaxA_1=4, BaxA_2=1, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=1, BaxA_2=2, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=2, BaxA_2=3, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=3, BaxA_2=4, BclxLM=None, Bcl2=None, CytoCM=5, BaxM=None, SmacM=None) % CytoCM(BakA=None, BaxA=5), BaxA_transport_binding_CytoCM_0_2kf, BaxA_transport_binding_CytoCM_0_1kr)
Rule('BaxA_self_catalyze_BaxM_0', BaxA(BaxA_1=None, BaxA_2=None, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) + BaxM(BidM=None, BaxA=None) | BaxA(BaxA_1=None, BaxA_2=None, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=1, SmacM=None) % BaxM(BidM=None, BaxA=1), BaxA_self_catalyze_BaxM_0_2kf, BaxA_self_catalyze_BaxM_0_1kr)
Rule('BaxA_self_catalyze_BaxM_1', BaxA(BaxA_1=None, BaxA_2=None, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=1, SmacM=None) % BaxM(BidM=None, BaxA=1) >> BaxA(BaxA_1=None, BaxA_2=None, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) + BaxA(BaxA_1=None, BaxA_2=None, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None), BaxA_self_catalyze_BaxM_1_1kc)
Rule('BaxC_BidM_catalysis_BaxM_0', BidM(BaxM=None, BaxC=1, Mcl1M=None, Bcl2=None, BclxLM=None, BakM=None) % BaxC(BidM=1) >> BidM(BaxM=None, BaxC=None, Mcl1M=None, Bcl2=None, BclxLM=None, BakM=None) + BaxM(BidM=None, BaxA=None), BaxC_BidM_catalysis_BaxM_0_1kc)
Rule('BidM_substrate_binding_BaxC_0', BidM(BaxM=None, BaxC=None, Mcl1M=None, Bcl2=None, BclxLM=None, BakM=None) + BaxC(BidM=None) | BidM(BaxM=None, BaxC=1, Mcl1M=None, Bcl2=None, BclxLM=None, BakM=None) % BaxC(BidM=1), BidM_substrate_binding_BaxC_0_2kf, BidM_substrate_binding_BaxC_0_1kr)
Rule('Mcl1M_inhibition_BidM_0', Mcl1M(BidM=None, NoxaM=None, BakA=None) + BidM(BaxM=None, BaxC=None, Mcl1M=None, Bcl2=None, BclxLM=None, BakM=None) | Mcl1M(BidM=1, NoxaM=None, BakA=None) % BidM(BaxM=None, BaxC=None, Mcl1M=1, Bcl2=None, BclxLM=None, BakM=None), Mcl1M_inhibition_BidM_0_2kf, Mcl1M_inhibition_BidM_0_1kr)
Rule('Bcl2_inhibition_BidM_0', Bcl2(BaxA=None, BidM=None, BadM=None) + BidM(BaxM=None, BaxC=None, Mcl1M=None, Bcl2=None, BclxLM=None, BakM=None) | Bcl2(BaxA=None, BidM=1, BadM=None) % BidM(BaxM=None, BaxC=None, Mcl1M=None, Bcl2=1, BclxLM=None, BakM=None), Bcl2_inhibition_BidM_0_2kf, Bcl2_inhibition_BidM_0_1kr)
Rule('BclxLM_inhibition_BidM_0', BclxLM(BaxA=None, BidM=None, BadM=None, BakA=None) + BidM(BaxM=None, BaxC=None, Mcl1M=None, Bcl2=None, BclxLM=None, BakM=None) | BclxLM(BaxA=None, BidM=1, BadM=None, BakA=None) % BidM(BaxM=None, BaxC=None, Mcl1M=None, Bcl2=None, BclxLM=1, BakM=None), BclxLM_inhibition_BidM_0_2kf, BclxLM_inhibition_BidM_0_1kr)
Rule('BakA_self_catalyze_BakM_0', BakA(BakA_1=None, BakA_2=None, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) + BakM(BakA=None, BidM=None) | BakA(BakA_1=None, BakA_2=None, CytoCM=None, BakM=1, SmacM=None, BclxLM=None, Mcl1M=None) % BakM(BakA=1, BidM=None), BakA_self_catalyze_BakM_0_2kf, BakA_self_catalyze_BakM_0_1kr)
Rule('BakA_self_catalyze_BakM_1', BakA(BakA_1=None, BakA_2=None, CytoCM=None, BakM=1, SmacM=None, BclxLM=None, Mcl1M=None) % BakM(BakA=1, BidM=None) >> BakA(BakA_1=None, BakA_2=None, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) + BakA(BakA_1=None, BakA_2=None, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None), BakA_self_catalyze_BakM_1_1kc)
Rule('BadM_inhibition_BclxLM_0', BadM(BclxLM=None, Bcl2=None) + BclxLM(BaxA=None, BidM=None, BadM=None, BakA=None) | BadM(BclxLM=1, Bcl2=None) % BclxLM(BaxA=None, BidM=None, BadM=1, BakA=None), BadM_inhibition_BclxLM_0_2kf, BadM_inhibition_BclxLM_0_1kr)
Rule('NoxaM_inhibition_Mcl1M_0', NoxaM(Mcl1M=None) + Mcl1M(BidM=None, NoxaM=None, BakA=None) | NoxaM(Mcl1M=1) % Mcl1M(BidM=None, NoxaM=1, BakA=None), NoxaM_inhibition_Mcl1M_0_2kf, NoxaM_inhibition_Mcl1M_0_1kr)
Rule('SmacM_BakA_transport_SmacC_0', BakA(BakA_1=4, BakA_2=1, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=1, BakA_2=2, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=2, BakA_2=3, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=3, BakA_2=4, CytoCM=None, BakM=None, SmacM=5, BclxLM=None, Mcl1M=None) % SmacM(BakA=5, BaxA=None) >> BakA(BakA_1=4, BakA_2=1, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=1, BakA_2=2, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=2, BakA_2=3, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=3, BakA_2=4, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) + SmacC(), SmacM_BakA_transport_SmacC_0_1kc)
Rule('SmacM_BaxA_transport_SmacC_0', BaxA(BaxA_1=4, BaxA_2=1, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=1, BaxA_2=2, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=2, BaxA_2=3, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=3, BaxA_2=4, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=5) % SmacM(BakA=None, BaxA=5) >> BaxA(BaxA_1=4, BaxA_2=1, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=1, BaxA_2=2, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=2, BaxA_2=3, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=3, BaxA_2=4, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) + SmacC(), SmacM_BaxA_transport_SmacC_0_1kc)
Rule('BakA_transport_binding_SmacM_0', BakA(BakA_1=4, BakA_2=1, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=1, BakA_2=2, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=2, BakA_2=3, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=3, BakA_2=4, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) + SmacM(BakA=None, BaxA=None) | BakA(BakA_1=4, BakA_2=1, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=1, BakA_2=2, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=2, BakA_2=3, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) % BakA(BakA_1=3, BakA_2=4, CytoCM=None, BakM=None, SmacM=5, BclxLM=None, Mcl1M=None) % SmacM(BakA=5, BaxA=None), BakA_transport_binding_SmacM_0_2kf, BakA_transport_binding_SmacM_0_1kr)
Rule('BaxA_transport_binding_SmacM_0', BaxA(BaxA_1=4, BaxA_2=1, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=1, BaxA_2=2, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=2, BaxA_2=3, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=3, BaxA_2=4, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) + SmacM(BakA=None, BaxA=None) | BaxA(BaxA_1=4, BaxA_2=1, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=1, BaxA_2=2, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=2, BaxA_2=3, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None) % BaxA(BaxA_1=3, BaxA_2=4, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=5) % SmacM(BakA=None, BaxA=5), BaxA_transport_binding_SmacM_0_2kf, BaxA_transport_binding_SmacM_0_1kr)
Rule('BclxLM_inhibition_BakA_0', BclxLM(BaxA=None, BidM=None, BadM=None, BakA=None) + BakA(BakA_1=None, BakA_2=None, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) | BclxLM(BaxA=None, BidM=None, BadM=None, BakA=1) % BakA(BakA_1=None, BakA_2=None, CytoCM=None, BakM=None, SmacM=None, BclxLM=1, Mcl1M=None), BclxLM_inhibition_BakA_0_2kf, BclxLM_inhibition_BakA_0_1kr)
Rule('Mcl1M_inhibition_BakA_0', Mcl1M(BidM=None, NoxaM=None, BakA=None) + BakA(BakA_1=None, BakA_2=None, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None) | Mcl1M(BidM=None, NoxaM=None, BakA=1) % BakA(BakA_1=None, BakA_2=None, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=1), Mcl1M_inhibition_BakA_0_2kf, Mcl1M_inhibition_BakA_0_1kr)
Rule('BakM_BidM_catalysis_BakA_0', BidM(BaxM=None, BaxC=None, Mcl1M=None, Bcl2=None, BclxLM=None, BakM=1) % BakM(BakA=None, BidM=1) >> BidM(BaxM=None, BaxC=None, Mcl1M=None, Bcl2=None, BclxLM=None, BakM=None) + BakA(BakA_1=None, BakA_2=None, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None), BakM_BidM_catalysis_BakA_0_1kc)
Rule('BidM_substrate_binding_BakM_0', BidM(BaxM=None, BaxC=None, Mcl1M=None, Bcl2=None, BclxLM=None, BakM=None) + BakM(BakA=None, BidM=None) | BidM(BaxM=None, BaxC=None, Mcl1M=None, Bcl2=None, BclxLM=None, BakM=1) % BakM(BakA=None, BidM=1), BidM_substrate_binding_BakM_0_2kf, BidM_substrate_binding_BakM_0_1kr)
Rule('BadM_inhibition_Bcl2_0', BadM(BclxLM=None, Bcl2=None) + Bcl2(BaxA=None, BidM=None, BadM=None) | BadM(BclxLM=None, Bcl2=1) % Bcl2(BaxA=None, BidM=None, BadM=1), BadM_inhibition_Bcl2_0_2kf, BadM_inhibition_Bcl2_0_1kr)

Initial(BaxC(BidM=None), BaxC_0)
Initial(BaxA(BaxA_1=None, BaxA_2=None, BclxLM=None, Bcl2=None, CytoCM=None, BaxM=None, SmacM=None), BaxA_0)
Initial(Mcl1M(BidM=None, NoxaM=None, BakA=None), Mcl1M_0)
Initial(NoxaM(Mcl1M=None), NoxaM_0)
Initial(BaxM(BidM=None, BaxA=None), BaxM_0)
Initial(BidM(BaxM=None, BaxC=None, Mcl1M=None, Bcl2=None, BclxLM=None, BakM=None), BidM_0)
Initial(BakM(BakA=None, BidM=None), BakM_0)
Initial(SmacM(BakA=None, BaxA=None), SmacM_0)
Initial(CytoCM(BakA=None, BaxA=None), CytoCM_0)
Initial(BclxLM(BaxA=None, BidM=None, BadM=None, BakA=None), BclxLM_0)
Initial(BadM(BclxLM=None, Bcl2=None), BadM_0)
Initial(CytoCC(), CytoCC_0)
Initial(SmacC(), SmacC_0)
Initial(BakA(BakA_1=None, BakA_2=None, CytoCM=None, BakM=None, SmacM=None, BclxLM=None, Mcl1M=None), BakA_0)
Initial(Bcl2(BaxA=None, BidM=None, BadM=None), Bcl2_0)

from sympy import Piecewise
Monomer('Timer')
Parameter('Timer_rate_0', 1.0)
Parameter('Timer_0', 0.0)
Observable('Timer_obs', Timer())
Rule('Timer_increment', None >> Timer(), Timer_rate_0)
Parameter('a_0', 45819.36)
Parameter('b_0', 6.44555891)
Parameter('c_0', 16987.9731)
Parameter('UB_0', 40000)
Expression('bid_rate', Piecewise((0, Timer_obs == 0.0), ((UB_0*b_0*c_0*((Timer_obs/a_0)**b_0)*(((Timer_obs/a_0)**b_0) + 1)**(-(c_0+1)))/Timer_obs, Timer_obs > 0.0), (0.01, True)))
Rule('Bid_increment', None >> BidM(BaxM=None, BaxC=None, Mcl1M=None, Bcl2=None, BclxLM=None, BakM=None), bid_rate)
Initial(Timer(), Timer_0)

# display

# t = np.linspace(0, 20160, 113)
# solve_mod = Solver(model, t)
# solve_mod.run()
#
# pl.figure(figsize=(16, 12))
# pl.plot(t, solve_mod.yobs['SmacC_obs']/(solve_mod.yobs['SmacC_obs']+solve_mod.yobs['SmacM_obs']), label="aSmac/Smac")
#
# from process_momp_data import process_data
# data = process_data('momp_data.csv')
# data = map(list, zip(*data))
# pl.plot(t, data[1], 'ro', c='g', label="IMS-RP (Smac)")
#
# pl.legend(loc='lower right', fontsize=20, numpoints=1)
# pl.xlabel("Time (s)", fontsize=20)
# pl.ylabel("Molecules/cell", fontsize=20)
# pl.title('earm data vs calibration', fontsize=22)
# pl.tick_params(labelsize=16)
# pl.xlim([0, 20200])
#
# pl.show()
